sensor_frame_id: "spin_lidar_pitch_hokuyo_laser_frame"
point_cloud_topic: "/elevation_mapping/cloud_in"
map_frame_id: "world"
robot_base_frame_id: "base_link"
robot_pose_with_covariance_topic: "/pose_cov"
robot_pose_cache_size: 500
track_point_frame_id: "base_link"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
